"""Added bar code support

Revision ID: 2bae154233e1
Revises: 7bb26929cac0
Create Date: 2022-05-16 01:39:40.400516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bae154233e1'
down_revision = '7bb26929cac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('bar_code', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'bar_code')
    # ### end Alembic commands ###
