"""Added stock management models

Revision ID: 660885b5c144
Revises: 111d8fb37093
Create Date: 2022-05-14 00:10:28.894030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660885b5c144'
down_revision = '111d8fb37093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('per_item_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'per_item_cost')
    op.drop_column('stock', 'cost')
    # ### end Alembic commands ###
