"""Added reference_id in receipts

Revision ID: f51ffa710bc5
Revises: 2bae154233e1
Create Date: 2022-05-16 02:07:37.781207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51ffa710bc5'
down_revision = '2bae154233e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('reference_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'reference_id')
    # ### end Alembic commands ###
